"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogTrigger,
} from "@/components/ui/dialog";
import { generateDemoImage } from "@/ai/flows/generate-demo-video";
import { useToast } from "@/hooks/use-toast";
import { Loader2, Film, Image as ImageIcon } from "lucide-react";
import { Button } from "../ui/button";
import Image from "next/image";

export function DemoVideoDialog({ children }: { children: React.ReactNode }) {
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();

  const handleGenerateImage = async () => {
    if (imageUrl) return; 

    setIsLoading(true);
    setError(null);
    try {
      const result = await generateDemoImage();
      setImageUrl(result.imageUrl);
    } catch (e) {
      console.error(e);
      const errorMessage = e instanceof Error ? e.message : "An unknown error occurred.";
      setError(errorMessage);
      toast({
        title: "Image Generation Failed",
        description: "Could not generate the AI demo image. Please try again later.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog onOpenChange={(open) => {
        if (open && !imageUrl && !isLoading) {
            handleGenerateImage();
        }
    }}>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="max-w-4xl">
        <DialogHeader>
          <DialogTitle>AI-Generated Platform Preview</DialogTitle>
          <DialogDescription>
            A glimpse of our platform's key features, generated by AI.
          </DialogDescription>
        </DialogHeader>
        <div className="aspect-video rounded-lg overflow-hidden border bg-muted flex items-center justify-center">
            {isLoading && (
                <div className="text-center text-muted-foreground space-y-4">
                    <Loader2 className="h-12 w-12 mx-auto animate-spin text-primary" />
                    <p className="font-semibold">Generating AI Image...</p>
                    <p className="text-sm">This may take a moment. Please wait.</p>
                </div>
            )}
            {error && !isLoading && (
                <div className="text-center text-destructive-foreground bg-destructive/80 p-8 rounded-md">
                    <p className="font-semibold">Generation Failed</p>
                    <p className="text-sm mt-2">{error}</p>
                    <Button variant="secondary" className="mt-4" onClick={handleGenerateImage}>
                        Retry
                    </Button>
                </div>
            )}
            {!isLoading && !error && imageUrl && (
                <Image
                    src={imageUrl}
                    alt="AI-generated demo of CarbonSight AI dashboard"
                    width={1280}
                    height={720}
                    className="object-cover w-full h-full"
                />
            )}
             {!isLoading && !error && !imageUrl && (
                <div className="text-center text-muted-foreground space-y-4">
                    <ImageIcon className="h-12 w-12 mx-auto text-primary" />
                    <p className="font-semibold">Ready to Generate Image</p>
                    <p className="text-sm">The AI-powered preview will start generating when you open this dialog.</p>
                </div>
            )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
